name: End-to-end tests Edge
on:
  push:
  workflow_dispatch:
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run E2E tests Edge
        uses: cypress-io/github-action@v5
        with:
          start: "npm run start:ci"
          wait-on: "http://localhost:8888"
          config: baseUrl=http://localhost:8888
          browser: edge
